import type { Metadata } from "next";
import "./globals.css";

import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

import { Inter, Poppins } from "next/font/google"
import LayoutContext from "@/components/common/LayoutContext/LayoutContext";

import { Toaster, toast } from 'sonner';
import Providers from "@/components/Admin/providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-heading",
})

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "Crystal Wall Art",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`antialiased ${inter.variable} ${poppins.variable}`}
      >
        <Toaster />
        <Providers>
          <LayoutContext>
            {children}
          </LayoutContext>
        </Providers>
      </body>
    </html>
  );
}
