import type { Metadata } from "next";
import "./globals.css";

import { cn } from "@/lib/utils";

import LayoutContext from "@/components/common/LayoutContext/LayoutContext";

import { Toaster } from "sonner";
import Providers from "@/components/Admin/providers";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Crystal Wall Art",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans")}>
      <body className="antialiased">
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://www.google.com/recaptcha/enterprise.js?render=6Le58AMtAAAAAM0cqBh6ng-cgWfA5U7Ps43OMnlB"
          strategy="afterInteractive"
        />

        <Toaster />

        <Providers>
          <LayoutContext>
            {children}
          </LayoutContext>
        </Providers>
      </body>
    </html>
  );
}