import type { Metadata } from "next";
import "./globals.css";

import LayoutContainer from "@/components/Container/LayoutContainer";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Crystal Wall Art",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`antialiased`}
      >
        <LayoutContainer>
          {children}
        </LayoutContainer>
      </body>
    </html>
  );
}
