import { Toaster } from "sonner";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import { Metadata } from "next";
import AdminLayout from "@/components/Admin/AdminLayout";
import "./globals.css";
import { NetworkAlert } from "@/components/Admin/NetworkAlert";
import Providers from "@/components/Admin/providers";

const geist = localFont({
  src: [
    {
      path: "../../public/fonts/geist/Geist-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/geist/Geist-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sans",
});

const inter = localFont({
  src: [
    {
      path: "../../public/fonts/inter/Inter-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/inter/Inter-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/inter/Inter-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sans",
});

const poppins = localFont({
  src: [
    {
      path: "../../public/fonts/poppins/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/poppins/Poppins-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/poppins/Poppins-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/poppins/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Admin - Crystal Wall Art",
  description: "Generated by create next app",
};

export default function AdminRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`antialiased ${inter.variable} ${poppins.variable}`}
      >
        <Toaster />
        <Providers>
          <AdminLayout>
            {children}
          </AdminLayout>
          <NetworkAlert />
        </Providers>
      </body>
    </html>
  );
}