import { Toaster } from "sonner";
import { Geist, Inter, Poppins } from "next/font/google";
import { cn } from "@/lib/utils";
import { Metadata } from "next";
import AdminLayout from "@/components/Admin/AdminLayout";
import "./globals.css";
import { NetworkAlert } from "@/components/Admin/NetworkAlert";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-heading",
})

export const metadata: Metadata = {
  title: "Admin - Crystal Wall Art",
  description: "Generated by create next app",
};

export default function AdminRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`antialiased ${inter.variable} ${poppins.variable}`}
      >
        <Toaster />
        <AdminLayout>
          {children}
        </AdminLayout>
        <NetworkAlert />
      </body>
    </html>
  );
}